// Generated by scripts/generate-scheme.ts — do not edit by hand.
// Seed #094F9A (HCT hue 262.5, chroma 49.3, tone 33.9).
// Regenerate with `pnpm scheme:generate`.

/** M3 reference tonal palettes. Only the tones the sys layer consumes are emitted. */
export const refPalettes = {
  primary: {
    0: '#000000',
    10: '#001b3d',
    20: '#003063',
    30: '#00468c',
    40: '#245eaa',
    50: '#4377c4',
    60: '#5f91e0',
    70: '#7bacfd',
    80: '#a9c7ff',
    90: '#d6e3ff',
    95: '#ecf0ff',
    99: '#fdfbff',
    100: '#ffffff',
  },
  secondary: {
    10: '#121c2b',
    20: '#283141',
    30: '#3e4758',
    40: '#555f71',
    80: '#bdc7dc',
    90: '#d9e3f9',
  },
  tertiary: {
    10: '#28132f',
    20: '#3f2845',
    30: '#563e5c',
    40: '#6f5675',
    80: '#dcbce1',
    90: '#f9d8fd',
  },
  neutral: {
    4: '#0d0e11',
    6: '#121316',
    10: '#1a1b1e',
    12: '#1e2023',
    17: '#292a2d',
    20: '#2f3033',
    22: '#343538',
    24: '#38393c',
    30: '#46474a',
    50: '#77777a',
    60: '#909094',
    70: '#ababaf',
    80: '#c7c6ca',
    87: '#dad9dd',
    90: '#e3e2e6',
    92: '#e9e7ec',
    94: '#efedf1',
    96: '#f4f3f7',
    98: '#faf9fd',
    99: '#fdfbff',
    100: '#ffffff',
  },
  neutralVariant: {
    30: '#44474e',
    50: '#74777f',
    60: '#8e9099',
    80: '#c4c6cf',
    90: '#e0e2ec',
  },
  error: {
    10: '#410002',
    20: '#690005',
    30: '#93000a',
    40: '#ba1a1a',
    80: '#ffb4ab',
    90: '#ffdad6',
  },
} as const;

export const refPaletteSeed = '#094F9A';
