import type { FhirRecord } from './registry';

/**
 * Compact, valid FHIR R4 example per registry type, shown as a disappearing placeholder row when a
 * type has no stored resources. Each covers the required elements plus the few that define the
 * resource, so the shape is obvious and the JSON works as a starting template. These are bundled
 * because the backend does not serve core `StructureDefinition`s (HAPI returns 404 for them).
 *
 * Keep them small and spec-correct: required elements first, then the defining ones.
 */
export const RESOURCE_EXAMPLES: Readonly<Record<string, FhirRecord>> = {
  Patient: {
    resourceType: 'Patient',
    id: 'example',
    active: true,
    name: [{ use: 'official', family: 'Doe', given: ['Jane'] }],
    gender: 'female',
    birthDate: '1990-04-12',
    telecom: [{ system: 'phone', value: '+254700000000', use: 'mobile' }],
  },
  Practitioner: {
    resourceType: 'Practitioner',
    id: 'example',
    active: true,
    identifier: [{ system: 'http://ohs.dev/identifiers/national-id', value: '12345678' }],
    name: [{ family: 'Achieng', given: ['Mary'] }],
    telecom: [{ system: 'email', value: 'mary.achieng@example.org', use: 'work' }],
  },
  PractitionerRole: {
    resourceType: 'PractitionerRole',
    id: 'example',
    active: true,
    practitioner: { reference: 'Practitioner/example' },
    organization: { reference: 'Organization/example' },
    code: [
      {
        coding: [
          {
            system: 'http://terminology.hl7.org/CodeSystem/practitioner-role',
            code: 'nurse',
            display: 'Nurse',
          },
        ],
      },
    ],
  },
  Organization: {
    resourceType: 'Organization',
    id: 'example',
    active: true,
    name: 'Demo Health Organization',
    telecom: [{ system: 'phone', value: '+254700000001' }],
  },
  Encounter: {
    resourceType: 'Encounter',
    id: 'example',
    status: 'finished',
    class: { system: 'http://terminology.hl7.org/CodeSystem/v3-ActCode', code: 'AMB', display: 'ambulatory' },
    type: [{ coding: [{ system: 'http://snomed.info/sct', code: '162673000', display: 'Outpatient visit' }] }],
    subject: { reference: 'Patient/example' },
    period: { start: '2026-01-15T09:00:00Z', end: '2026-01-15T09:30:00Z' },
  },
  Observation: {
    resourceType: 'Observation',
    id: 'example',
    status: 'final',
    code: { coding: [{ system: 'http://loinc.org', code: '29463-7', display: 'Body weight' }] },
    subject: { reference: 'Patient/example' },
    effectiveDateTime: '2026-01-15T09:10:00Z',
    valueQuantity: { value: 68.5, unit: 'kg', system: 'http://unitsofmeasure.org', code: 'kg' },
  },
  Condition: {
    resourceType: 'Condition',
    id: 'example',
    clinicalStatus: {
      coding: [{ system: 'http://terminology.hl7.org/CodeSystem/condition-clinical', code: 'active' }],
    },
    code: { coding: [{ system: 'http://snomed.info/sct', code: '38341003', display: 'Hypertension' }] },
    subject: { reference: 'Patient/example' },
    recordedDate: '2026-01-15',
  },
  Procedure: {
    resourceType: 'Procedure',
    id: 'example',
    status: 'completed',
    code: { coding: [{ system: 'http://snomed.info/sct', code: '80146002', display: 'Appendectomy' }] },
    subject: { reference: 'Patient/example' },
    performedDateTime: '2026-01-15T10:00:00Z',
  },
  Questionnaire: {
    resourceType: 'Questionnaire',
    id: 'example',
    status: 'active',
    name: 'IntakeForm',
    title: 'Patient intake form',
    item: [{ linkId: '1', text: 'What is your full name?', type: 'string' }],
  },
  QuestionnaireResponse: {
    resourceType: 'QuestionnaireResponse',
    id: 'example',
    status: 'completed',
    questionnaire: 'Questionnaire/example',
    subject: { reference: 'Patient/example' },
    authored: '2026-01-15T09:20:00Z',
    item: [{ linkId: '1', answer: [{ valueString: 'Jane Doe' }] }],
  },
  RelatedPerson: {
    resourceType: 'RelatedPerson',
    id: 'example',
    active: true,
    patient: { reference: 'Patient/example' },
    relationship: [
      { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/v3-RoleCode', code: 'MTH', display: 'mother' }] },
    ],
    name: [{ family: 'Doe', given: ['Alice'] }],
  },
  MedicationRequest: {
    resourceType: 'MedicationRequest',
    id: 'example',
    status: 'active',
    intent: 'order',
    medicationCodeableConcept: {
      coding: [{ system: 'http://snomed.info/sct', code: '387517004', display: 'Paracetamol' }],
    },
    subject: { reference: 'Patient/example' },
    authoredOn: '2026-01-15',
  },
  MedicationStatement: {
    resourceType: 'MedicationStatement',
    id: 'example',
    status: 'active',
    medicationCodeableConcept: {
      coding: [{ system: 'http://snomed.info/sct', code: '387517004', display: 'Paracetamol' }],
    },
    subject: { reference: 'Patient/example' },
    effectiveDateTime: '2026-01-15',
  },
  AllergyIntolerance: {
    resourceType: 'AllergyIntolerance',
    id: 'example',
    clinicalStatus: {
      coding: [{ system: 'http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical', code: 'active' }],
    },
    code: { coding: [{ system: 'http://snomed.info/sct', code: '764146007', display: 'Penicillin' }] },
    patient: { reference: 'Patient/example' },
    recordedDate: '2026-01-15',
  },
  Appointment: {
    resourceType: 'Appointment',
    id: 'example',
    status: 'booked',
    description: 'Antenatal check-up',
    start: '2026-02-01T09:00:00Z',
    end: '2026-02-01T09:30:00Z',
    participant: [{ actor: { reference: 'Patient/example' }, status: 'accepted' }],
  },
  Immunization: {
    resourceType: 'Immunization',
    id: 'example',
    status: 'completed',
    vaccineCode: { coding: [{ system: 'http://snomed.info/sct', code: '1119349007', display: 'COVID-19 vaccine' }] },
    patient: { reference: 'Patient/example' },
    occurrenceDateTime: '2026-01-15',
  },
  DiagnosticReport: {
    resourceType: 'DiagnosticReport',
    id: 'example',
    status: 'final',
    code: { coding: [{ system: 'http://loinc.org', code: '58410-2', display: 'Complete blood count panel' }] },
    subject: { reference: 'Patient/example' },
    effectiveDateTime: '2026-01-15T09:30:00Z',
    conclusion: 'Within normal limits.',
  },
  CarePlan: {
    resourceType: 'CarePlan',
    id: 'example',
    status: 'active',
    intent: 'plan',
    title: 'Hypertension management plan',
    subject: { reference: 'Patient/example' },
    period: { start: '2026-01-15' },
  },
  CareTeam: {
    resourceType: 'CareTeam',
    id: 'example',
    status: 'active',
    name: 'Primary Care Team',
    subject: { reference: 'Patient/example' },
    participant: [{ member: { reference: 'Practitioner/example' } }],
  },
  Claim: {
    resourceType: 'Claim',
    id: 'example',
    status: 'active',
    type: { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/claim-type', code: 'professional' }] },
    use: 'claim',
    patient: { reference: 'Patient/example' },
    created: '2026-01-15',
    provider: { reference: 'Organization/example' },
    priority: { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/processpriority', code: 'normal' }] },
  },
  CodeSystem: {
    resourceType: 'CodeSystem',
    id: 'example',
    url: 'http://ohs.dev/CodeSystem/example',
    status: 'active',
    content: 'complete',
    name: 'ExampleCodeSystem',
    concept: [{ code: 'a', display: 'Option A' }],
  },
  Coverage: {
    resourceType: 'Coverage',
    id: 'example',
    status: 'active',
    type: {
      coding: [
        { system: 'http://terminology.hl7.org/CodeSystem/v3-ActCode', code: 'EHCPOL', display: 'Extended healthcare' },
      ],
    },
    beneficiary: { reference: 'Patient/example' },
    payor: [{ reference: 'Organization/example' }],
  },
  DocumentReference: {
    resourceType: 'DocumentReference',
    id: 'example',
    status: 'current',
    type: { coding: [{ system: 'http://loinc.org', code: '34133-9', display: 'Summary of episode note' }] },
    subject: { reference: 'Patient/example' },
    date: '2026-01-15T09:40:00Z',
    content: [{ attachment: { contentType: 'application/pdf', url: 'https://example.org/summary.pdf' } }],
  },
  Goal: {
    resourceType: 'Goal',
    id: 'example',
    lifecycleStatus: 'active',
    description: { text: 'Reduce blood pressure below 130/80' },
    subject: { reference: 'Patient/example' },
  },
  Group: {
    resourceType: 'Group',
    id: 'example',
    type: 'person',
    actual: true,
    name: 'Antenatal cohort',
    member: [{ entity: { reference: 'Patient/example' } }],
  },
  Location: {
    resourceType: 'Location',
    id: 'example',
    status: 'active',
    name: 'Demo Clinic',
    mode: 'instance',
    address: { city: 'Nairobi', country: 'KE' },
  },
  MeasureReport: {
    resourceType: 'MeasureReport',
    id: 'example',
    status: 'complete',
    type: 'summary',
    measure: 'http://ohs.dev/Measure/example',
    period: { start: '2026-01-01', end: '2026-01-31' },
  },
  Medication: {
    resourceType: 'Medication',
    id: 'example',
    status: 'active',
    code: { coding: [{ system: 'http://snomed.info/sct', code: '387517004', display: 'Paracetamol' }] },
    form: { coding: [{ system: 'http://snomed.info/sct', code: '385055001', display: 'Tablet' }] },
  },
  MedicationAdministration: {
    resourceType: 'MedicationAdministration',
    id: 'example',
    status: 'completed',
    medicationCodeableConcept: {
      coding: [{ system: 'http://snomed.info/sct', code: '387517004', display: 'Paracetamol' }],
    },
    subject: { reference: 'Patient/example' },
    effectiveDateTime: '2026-01-15T10:15:00Z',
  },
  PlanDefinition: {
    resourceType: 'PlanDefinition',
    id: 'example',
    status: 'active',
    name: 'AntenatalPathway',
    title: 'Antenatal care pathway',
    type: { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/plan-definition-type', code: 'clinical-protocol' }] },
  },
  ServiceRequest: {
    resourceType: 'ServiceRequest',
    id: 'example',
    status: 'active',
    intent: 'order',
    code: { coding: [{ system: 'http://loinc.org', code: '58410-2', display: 'Complete blood count panel' }] },
    subject: { reference: 'Patient/example' },
    authoredOn: '2026-01-15',
  },
  Specimen: {
    resourceType: 'Specimen',
    id: 'example',
    status: 'available',
    type: { coding: [{ system: 'http://snomed.info/sct', code: '119297000', display: 'Blood specimen' }] },
    subject: { reference: 'Patient/example' },
    collection: { collectedDateTime: '2026-01-15T09:05:00Z' },
  },
  SupplyDelivery: {
    resourceType: 'SupplyDelivery',
    id: 'example',
    status: 'completed',
    patient: { reference: 'Patient/example' },
    type: { coding: [{ system: 'http://terminology.hl7.org/CodeSystem/supply-item-type', code: 'device' }] },
    occurrenceDateTime: '2026-01-15',
  },
  Task: {
    resourceType: 'Task',
    id: 'example',
    status: 'requested',
    intent: 'order',
    code: { coding: [{ system: 'http://hl7.org/fhir/CodeSystem/task-code', code: 'fulfill' }] },
    for: { reference: 'Patient/example' },
    authoredOn: '2026-01-15T09:00:00Z',
  },
};

/** Example resource for a type, or undefined when none is bundled. */
export function exampleFor(resourceType: string): FhirRecord | undefined {
  return RESOURCE_EXAMPLES[resourceType];
}
