/**
 * Generates the M3 reference tonal palettes for the core theme layer.
 *
 *   pnpm scheme:generate            # regenerate from the brand seed
 *   pnpm scheme:generate '#0F766E'  # try another seed
 *
 * Build-time only: `@material/material-color-utilities` is a root devDependency and must never reach
 * the library bundle (`scripts/check-core-bundle-size.mjs` guards ~18 KiB of headroom). This writes a
 * committed TS file of plain hex strings, which is what core actually imports.
 *
 * Must run under `tsx`, not `node` — the published 0.4.0 ESM uses extensionless relative imports that
 * Node's resolver rejects.
 */

import { writeFileSync } from 'node:fs';
import { CorePalette, Hct, argbFromHex, hexFromArgb } from '@material/material-color-utilities';

const DEFAULT_SEED = '#094F9A';
const OUTPUT = 'packages/ohs-player-web-core/src/theme/palettes.ts';

/** Only the tones the sys layer consumes, to keep the bundle lean. */
const TONES = {
  primary: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 99, 100],
  secondary: [10, 20, 30, 40, 80, 90],
  tertiary: [10, 20, 30, 40, 80, 90],
  neutral: [4, 6, 10, 12, 17, 20, 22, 24, 30, 50, 60, 70, 80, 87, 90, 92, 94, 96, 98, 99, 100],
  neutralVariant: [30, 50, 60, 80, 90],
  error: [10, 20, 30, 40, 80, 90],
} as const;

/**
 * Reviewed, contrast-verified values. Asserted so a library upgrade that shifts the colour science
 * fails loudly instead of silently rewriting the palette.
 */
const EXPECTED_FOR_DEFAULT_SEED: Record<string, string> = {
  'primary.10': '#001b3d',
  'primary.40': '#245eaa',
  'primary.80': '#a9c7ff',
  'primary.90': '#d6e3ff',
  'neutral.90': '#e3e2e6',
  'neutralVariant.50': '#74777f',
  'neutralVariant.60': '#8e9099',
  'error.40': '#ba1a1a',
  'error.80': '#ffb4ab',
};

const seed = process.argv[2] ?? DEFAULT_SEED;
const seedArgb = argbFromHex(seed);
const hct = Hct.fromInt(seedArgb);
const core = CorePalette.of(seedArgb);

const palettes = {
  primary: core.a1,
  secondary: core.a2,
  tertiary: core.a3,
  neutral: core.n1,
  neutralVariant: core.n2,
  error: core.error,
} as const;

type PaletteName = keyof typeof TONES;

const generated = new Map<PaletteName, Array<[number, string]>>();
for (const name of Object.keys(TONES) as PaletteName[]) {
  generated.set(
    name,
    TONES[name].map((tone) => [tone, hexFromArgb(palettes[name].tone(tone))]),
  );
}

if (seed.toLowerCase() === DEFAULT_SEED.toLowerCase()) {
  const mismatches: string[] = [];
  for (const [key, expected] of Object.entries(EXPECTED_FOR_DEFAULT_SEED)) {
    const [name, tone] = key.split('.') as [PaletteName, string];
    const actual = generated.get(name)?.find(([t]) => t === Number(tone))?.[1];
    if (actual !== expected)
      mismatches.push(`  ${key}: generated ${actual ?? 'nothing'}, doc says ${expected}`);
  }
  if (mismatches.length > 0) {
    console.error(
      `Generated palette diverges from the reviewed values:\n${mismatches.join('\n')}\n\n` +
        'Investigate before regenerating.',
    );
    process.exit(1);
  }
}

const body = (Object.keys(TONES) as PaletteName[])
  .map((name) => {
    const entries = generated
      .get(name)!
      .map(([tone, hex]) => `    ${tone}: '${hex}',`)
      .join('\n');
    return `  ${name}: {\n${entries}\n  },`;
  })
  .join('\n');

writeFileSync(
  OUTPUT,
  `// Generated by scripts/generate-scheme.ts — do not edit by hand.
// Seed ${seed} (HCT hue ${hct.hue.toFixed(1)}, chroma ${hct.chroma.toFixed(1)}, tone ${hct.tone.toFixed(1)}).
// Regenerate with \`pnpm scheme:generate\`.

/** M3 reference tonal palettes. Only the tones the sys layer consumes are emitted. */
export const refPalettes = {
${body}
} as const;

export const refPaletteSeed = '${seed}';
`,
  'utf8',
);

const total = [...generated.values()].reduce((n, list) => n + list.length, 0);
console.log(`Wrote ${OUTPUT}: ${total} tones across ${generated.size} palettes from seed ${seed}.`);
