/**
 * Generates the app's icon set from Material Symbols SVGs.
 *
 *   pnpm icons:generate
 *
 * Build-time only: `@material-symbols/svg-400` is a root devDependency and must never reach the app
 * bundle. Emitting committed path data keeps the payload to the icons actually used (~400 bytes each)
 * instead of the 3.8 MB variable font, and avoids the ligature flash a font would introduce.
 */

import { readFileSync, writeFileSync } from 'node:fs';

const SVG_DIR = 'node_modules/@material-symbols/svg-400/outlined';
const OUTPUT = 'apps/ohs-player-web/src/components/ui/icons.tsx';

/** Exported component name -> Material Symbols file stem. */
const ICONS: Record<string, string> = {
  IconAccountCircle: 'account_circle',
  IconAccountCircleFill: 'account_circle-fill',
  IconAdd: 'add',
  IconAddCircle: 'add_circle',
  IconArrowOutward: 'arrow_outward',
  IconArrowRight: 'arrow_forward',
  // Trend arrows: Figma uses Remix arrow-right-up-line / arrow-left-down-line; these are the
  // geometrically equivalent Material Symbols, so the dashboard keeps one icon dependency.
  IconArrowUpRight: 'north_east',
  IconArrowDownLeft: 'south_west',
  IconArrowDropDown: 'arrow_drop_down',
  IconBriefcase: 'work',
  IconBriefcaseFill: 'work-fill',
  // Material Symbols has no distinct `domain-fill`; account_balance is the nearest institution
  // glyph that ships one, which the nav's outlined/filled active state needs.
  IconBuilding: 'account_balance',
  IconBuildingFill: 'account_balance-fill',
  IconBuildings: 'apartment',
  IconCheckboxBlank: 'check_box_outline_blank',
  IconCheck: 'check',
  IconCheckCircleFill: 'check_circle-fill',
  IconChevronDown: 'keyboard_arrow_down',
  IconToday: 'today-fill',
  IconChevronLeft: 'chevron_left',
  IconChevronRight: 'chevron_right',
  IconClose: 'close',
  IconCopy: 'content_copy',
  IconDashboard: 'dashboard',
  IconDashboardFill: 'dashboard-fill',
  IconDatabase: 'database',
  IconDatabaseFill: 'database-fill',
  IconDelete: 'delete',
  IconDownload: 'download',
  IconEdit: 'edit',
  IconErrorFill: 'error-fill',
  IconFileList: 'list_alt',
  IconFlash: 'bolt',
  IconGroup: 'group',
  IconGuide: 'menu_book',
  IconInfo: 'info',
  IconLock: 'lock',
  IconMagic: 'wand_stars',
  IconMagicFill: 'wand_stars-fill',
  IconMapPin: 'location_on',
  IconMapPinFill: 'location_on-fill',
  IconMenu: 'menu',
  IconMoon: 'dark_mode',
  IconMore: 'more_vert',
  IconNotification: 'notifications',
  IconSearch: 'search',
  IconSubdirectory: 'subdirectory_arrow_right',
  IconSun: 'light_mode',
  IconTeam: 'groups',
  IconTeamFill: 'groups-fill',
  IconTree: 'account_tree',
  IconUpload: 'cloud_upload',
  IconUser: 'person',
  IconUserFill: 'person-fill',
  IconVisibilityOff: 'visibility_off',
  IconWarning: 'warning',
};

function pathData(stem: string): string {
  const svg = readFileSync(`${SVG_DIR}/${stem}.svg`, 'utf8');
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length === 0) throw new Error(`No path found in ${stem}.svg`);
  return paths.join(' ');
}

const missing = Object.entries(ICONS).filter(([, stem]) => {
  try {
    pathData(stem);
    return false;
  } catch {
    return true;
  }
});
if (missing.length > 0) {
  console.error(
    `Material Symbols has no icon for:\n${missing.map(([n, s]) => `  ${n} -> ${s}`).join('\n')}`,
  );
  process.exit(1);
}

const components = Object.entries(ICONS)
  .map(([name, stem]) => `export const ${name} = makeIcon(\n  '${pathData(stem)}',\n);`)
  .join('\n\n');

writeFileSync(
  OUTPUT,
  `// Generated by scripts/generate-icons.ts — do not edit by hand.
// Material Symbols Outlined, weight 400. Regenerate with \`pnpm icons:generate\`.
import type { SVGProps } from 'react';

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'width' | 'height'> {
  /** Rendered width and height in px. */
  size?: number;
}

export type IconComponent = (props: IconProps) => React.ReactElement;

function makeIcon(d: string): IconComponent {
  return function Icon({ size = 24, ...rest }: IconProps): React.ReactElement {
    return (
      <svg
        width={size}
        height={size}
        viewBox="0 -960 960 960"
        fill="currentColor"
        aria-hidden={rest['aria-label'] ? undefined : true}
        focusable="false"
        {...rest}
      >
        <path d={d} />
      </svg>
    );
  };
}

${components}
`,
  'utf8',
);

console.log(`Wrote ${OUTPUT}: ${Object.keys(ICONS).length} icons.`);
